DEFINE
	// ============================================================================
	// Basic Columns
	// ============================================================================
	
	// 1.1 SUM PL
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 1.1 SUM PL] = SUM('Month_Variance_Analysis_Results'[PL])

	// 1.2 SUM AC
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 1.2 SUM AC] = SUM('Month_Variance_Analysis_Results'[AC])
	
	// 1.3 SUM FC
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 1.3 SUM FC] = SUM('Month_Variance_Analysis_Results'[FC])
	
	// 1.4 MAX of PL, AC, FC
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 1.4 MAX of PL, AC, FC] = IF(
		ISBLANK([A7D3 1.3 SUM FC]), 
  		if(
			[A7D3 1.2 SUM AC]>[A7D3 1.1 SUM PL], 
			[A7D3 1.2 SUM AC], 
			[A7D3 1.1 SUM PL]
		),
  		if(
			[A7D3 1.1 SUM PL]>[A7D3 1.3 SUM FC], 
			[A7D3 1.1 SUM PL], 
			[A7D3 1.3 SUM FC]
		)
  	)

	// 1.5 MIN of PL, AC, FC
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 1.5 MIN of PL, AC, FC] = IF(
		ISBLANK([A7D3 1.3 SUM FC]), 
  		if(
			[A7D3 1.2 SUM AC]<[A7D3 1.1 SUM PL],
			[A7D3 1.2 SUM AC],
			[A7D3 1.1 SUM PL]
		),
  		if(
			[A7D3 1.1 SUM PL]<[A7D3 1.3 SUM FC], 
			[A7D3 1.1 SUM PL],
			[A7D3 1.3 SUM FC]
		)
	)
	
	// 1.6 DELTA from AC or FC to PL
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 1.6 DELTA from AC or FC to PL] = IF(
		ISBLANK([A7D3 1.3 SUM FC]), 
		[A7D3 1.2 SUM AC] - [A7D3 1.1 SUM PL], 
		[A7D3 1.3 SUM FC] - [A7D3 1.1 SUM PL]
	)
	
	// 1.7 DATA LABEL COLOR TOP
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 1.7 DATA LABEL COLOR TOP] = IF(
		ISBLANK([A7D3 1.3 SUM FC]), 
		if(
			[A7D3 1.6 DELTA from AC or FC to PL] > 0,
			"#000000",
			"#B3B3B3"
		),
		if(
			[A7D3 1.6 DELTA from AC or FC to PL] > 0,
			"#118DFF",
			"#B3B3B3"
		)
	)
		
	// 1.8 DATA LABEL COLOR TOP
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 1.8 DATA LABEL COLOR BOT] = IF(
		ISBLANK([A7D3 1.3 SUM FC]), 
		if(
			[A7D3 1.6 DELTA from AC or FC to PL] < 0,
			"#000000",
			"#B3B3B3"
		),
		if(
			[A7D3 1.6 DELTA from AC or FC to PL] < 0,
			"#118DFF",
			"#B3B3B3"
		)
	)

	// ============================================================================
	// Delta Chart Preparations
	// ============================================================================
	
	// 2.1 MAX GLOBAL PL, AC, FC
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 2.1 MAX GLOBAL PL, AC, FC] = MAXX(
		ALLSELECTED('Month_Variance_Analysis_Results'), 
		[A7D3 1.4 MAX of PL, AC, FC]
	)
	
	// 2.2 Y AXIS HEIGHT
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 2.2 Y AXIS HEIGHT] = [A7D3 2.1 MAX GLOBAL PL, AC, FC] * 4.8
	
	// ============================================================================
	// Delta Chart 1
	// ============================================================================
	
	// 3.1 DELTA LINE POSITIVE
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 3.1 DELTA LINE POSITIVE] = [A7D3 2.1 MAX GLOBAL PL, AC, FC] * 2.3
	
	// 3.2 Delta Line NEGATIVE
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 3.2 DELTA LINE NEGATIVE] = [A7D3 3.1 DELTA LINE POSITIVE]
	
	// 3.3 Delta Line NEUTRAL
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 3.3 DELTA LINE NEUTRAL] = [A7D3 3.1 DELTA LINE POSITIVE]
	
	// Line Label
    MEASURE 'Month_Variance_Analysis_Results'[ΔPL] = [A7D3 3.1 DELTA LINE POSITIVE]
	
	// 3.4 DELTA LINE POSITIVE VALUES
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 3.4 DELTA LINE POSITIVE VALUES] = IF(
		ISBLANK([A7D3 1.3 SUM FC]),
		IF(
			[A7D3 1.6 DELTA from AC or FC to PL] >0, 
			[A7D3 3.1 DELTA LINE POSITIVE] + [A7D3 1.6 DELTA from AC or FC to PL], 
			blank()
		)
	)
	
	// 3.5 DELTA LINE NEGATIVE VALUES
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 3.5 DELTA LINE NEGATIVE VALUES] = IF(
		ISBLANK([A7D3 1.3 SUM FC]),
		IF(
			[A7D3 1.6 DELTA from AC or FC to PL] <0, 
			[A7D3 3.2 DELTA LINE NEGATIVE] + [A7D3 1.6 DELTA from AC or FC to PL], 
			blank()
		)
	)
	
	// 3.6 DELTA LINE NEUTRAL POSITIVE VALUES
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 3.6 DELTA LINE NEUTRAL POSITIVE VALUES] = IF(
		ISBLANK([A7D3 1.3 SUM FC]),
		BLANK(),
		IF(
			[A7D3 1.6 DELTA from AC or FC to PL] >0, 
			[A7D3 3.3 DELTA LINE NEUTRAL] + [A7D3 1.6 DELTA from AC or FC to PL], 
			blank()
		)
	)
	
	// 3.7 DELTA LINE NEUTRAL NEGATIVE VALUES
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 3.7 DELTA LINE NEUTRAL NEGATIVE VALUES] = IF(
		ISBLANK([A7D3 1.3 SUM FC]),
		BLANK(),
		IF(
			[A7D3 1.6 DELTA from AC or FC to PL] <0, 
			[A7D3 3.3 DELTA LINE NEUTRAL] + [A7D3 1.6 DELTA from AC or FC to PL], 
			blank()
		)
	)
	
	// ============================================================================
	// Delta Chart 2 (Percentage)
	// ============================================================================
	
	// 4.1 DELTA % LINE POSITIVE
	MEASURE 'Month_Variance_Analysis_Results'[A7D3 4.1 DELTA % LINE POSITIVE] = [A7D3 2.1 MAX GLOBAL PL, AC, FC] * 3.8
	
	// 4.2 DELTA % LINE NEGATIVE
	MEASURE 'Month_Variance_Analysis_Results'[A7D3 4.2 DELTA % LINE NEGATIVE] = [A7D3 4.1 DELTA % LINE POSITIVE]
	
	// 4.3 DELTA % LINE NEUTRAL
	MEASURE 'Month_Variance_Analysis_Results'[A7D3 4.3 DELTA % LINE NEUTRAL] = [A7D3 4.1 DELTA % LINE POSITIVE]
	
	// Line Label
	MEASURE 'Month_Variance_Analysis_Results'[ΔPL%] = [A7D3 4.1 DELTA % LINE POSITIVE]
	
	// 4.4 DELTA from AC or FC to PL in %
	MEASURE 'Month_Variance_Analysis_Results'[A7D3 4.4 DELTA from AC or FC to PL in %] = DIVIDE ([A7D3 1.6 DELTA from AC or FC to PL], [A7D3 1.1 SUM PL])
	
	// 4.5 Percentage Bar Modifier
	MEASURE 'Month_Variance_Analysis_Results'[A7D3 4.5 Percentage Bar Modifier] = DIVIDE(
		[A7D3 2.1 MAX GLOBAL PL, AC, FC], 
		MAXX(
			ALLSELECTED('Month_Variance_Analysis_Results'), 
			[A7D3 4.4 DELTA from AC or FC to PL in %]
		)
	)
	
	// 4.6 DELTA LINE % POSITIVE VALUES
	MEASURE 'Month_Variance_Analysis_Results'[A7D3 4.6 DELTA LINE % POSITIVE VALUES] = IF(
		ISBLANK([A7D3 1.3 SUM FC]),
		IF(
			[A7D3 4.4 DELTA from AC or FC to PL in %] >0,
			[A7D3 4.1 DELTA % LINE POSITIVE] + [A7D3 4.4 DELTA from AC or FC to PL in %]*[A7D3 4.5 Percentage Bar Modifier],
			blank()
		)
	)
	
	// 4.7 DELTA LINE % NEGATIVE VALUES
	MEASURE 'Month_Variance_Analysis_Results'[A7D3 4.7 DELTA LINE % NEGATIVE VALUES] = IF(
		ISBLANK([A7D3 1.3 SUM FC]),
		IF(
			[A7D3 4.4 DELTA from AC or FC to PL in %] <0,
			[A7D3 4.2 DELTA % LINE NEGATIVE] + [A7D3 4.4 DELTA from AC or FC to PL in %]*[A7D3 4.5 Percentage Bar Modifier],
			blank()
		)
	)
	
	// 4.8 DELTA LINE % NEUTRAL POSITIVE VALUES
	MEASURE 'Month_Variance_Analysis_Results'[A7D3 4.8 DELTA LINE % NEUTRAL POSITIVE VALUES] = IF(
		ISBLANK([A7D3 1.3 SUM FC]),
		BLANK(),
		IF(
			[A7D3 4.4 DELTA from AC or FC to PL in %] >0,
			[A7D3 4.1 DELTA % LINE POSITIVE] + [A7D3 4.4 DELTA from AC or FC to PL in %]*[A7D3 4.5 Percentage Bar Modifier],
			blank()
		)
	)
	
	// 4.9 DELTA LINE % NEUTRAL NEGATIVE VALUES
	MEASURE 'Month_Variance_Analysis_Results'[A7D3 4.9 DELTA LINE % NEUTRAL NEGATIVE VALUES] = IF(
		ISBLANK([A7D3 1.3 SUM FC]),
		BLANK(),
		IF(
			[A7D3 4.4 DELTA from AC or FC to PL in %] <0,
			[A7D3 4.2 DELTA % LINE NEGATIVE] + [A7D3 4.4 DELTA from AC or FC to PL in %]*[A7D3 4.5 Percentage Bar Modifier],
			blank()
		)
	)
	
	// 4.10 DELTA % LINE VALUE LABEL COLUMN
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 4.10 DELTA % LINE VALUE LABEL COLUMN] = IF(
		[A7D3 4.4 DELTA from AC or FC to PL in %] < 0,
		[A7D3 4.1 DELTA % LINE POSITIVE]* 0.92 + [A7D3 4.4 DELTA from AC or FC to PL in %]*[A7D3 4.5 Percentage Bar Modifier],
		[A7D3 4.1 DELTA % LINE POSITIVE] + [A7D3 4.4 DELTA from AC or FC to PL in %]*[A7D3 4.5 Percentage Bar Modifier]
	)
	
	// 4.11 DELTA % LINE VALUE LABEL
    MEASURE 'Month_Variance_Analysis_Results'[A7D3 4.11 DELTA % LINE VALUE LABEL] = FORMAT(DIVIDE([A7D3 1.6 DELTA from AC or FC to PL], [A7D3 1.1 SUM PL]), "0%")
